<?php
/**
 * Copyright © MagePal LLC. All rights reserved.
 * See COPYING.txt for license details.
 * http://www.pbyteshub.com | support@pbyteshub.com
 */
?>

<?php /** @var $block Pbyteshub\Smtp\Block\Adminhtml\System\Config\ValidateConfigButton **/ ?>
<?= $block->getButtonHtml() ?>

<script type="text/x-magento-init">
    {
        "#Smtp_debug_result_button": {
            "pbyteshubSmtpValidateConfig": {
                "postUrl":"<?= $block->escapeUrl($block->getAdminUrl()) ?>"
            }
        }
    }
</script>
